In [1]:
import numpy as np
import pandas as pd

In [2]:
customers = pd.read_csv("../data/customers.csv")
orders = pd.read_csv("../data/orders.csv")
products = pd.read_csv("../data/products.csv")

customers.head()

         id             name    segment           state             city
0  CG-12520      Claire Gute   Consumer        Kentucky        Henderson
1  DV-13045  Darrin Van Huff  Corporate      California      Los Angeles
2  SO-20335   Sean O'Donnell   Consumer         Florida  Fort Lauderdale
3  BH-11710  Brosina Hoffman   Consumer      California      Los Angeles
4  AA-10480     Andrew Allen   Consumer  North Carolina          Concord

In [3]:
print(customers.info())
print(orders.info())
print(products.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 793 entries, 0 to 792
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       793 non-null    object
 1   name     793 non-null    object
 2   segment  793 non-null    object
 3   state    793 non-null    object
 4   city     793 non-null    object
dtypes: object(5)
memory usage: 31.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5009 entries, 0 to 5008
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           5009 non-null   int64
 1   order_date   5009 non-null   object
 2   ship_mode    5009 non-null   object
 3   customer_id  5009 non-null   object
 4   sales        5009 non-null   float64
dtypes: float64(1), int64(1), object(3)
memory usage: 195.8+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150150 entries, 0 to 150149
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   id           150150 non-null  int64
 1   store_id     150150 non-null  int64
 2   total_price  150149 non-null  float64
 3   base_price   150150 non-null  float64
 4   units_sold   150150 non-null  int64
dtypes: float64(2), int64(3)
memory usage: 5.7 MB
None

In [4]:
customers = customers.dropna()
orders = orders.dropna()
products = products.dropna()

In [5]:
orders['order_date'] = pd.to_datetime(orders['order_date'])

In [6]:
df = orders.merge(customers, left_on="customer_id", right_on="id", suffixes=('', '_cust'))
df = df.merge(products, left_on="id", right_on="id", suffixes=('', '_prod'))
df = df.drop("id_cust", axis=1)

In [7]:
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month

In [8]:
df.to_csv("../data/cleaned_data.csv", index=False)

In [9]:
df.head()

,id,order_date,ship_mode,customer_id,sales,name,segment,state,city,store_id,total_price,base_price,units_sold,year,month
0,100293,2014-03-14,Standard,NF-18475,91.056,Neil Franzosisch,Home Office,Illinois,Rockford,9132,209.4750,209.4750,59,2014,3
1,100328,2014-01-28,Standard,JC-15340,3.928,Jasper Cacioppo,Consumer,California,Los Angeles,9164,140.3625,166.0125,46,2014,1
2,100363,2014-04-08,Standard,JM-15655,21.376,Jim Mitchum,Corporate,New Jersey,Bridgeton,9190,164.5875,164.5875,24,2014,4
3,100391,2014-05-25,Standard,BW-11065,14.620,Barry Weirich,Consumer,North Carolina,Raleigh,9221,230.1375,230.1375,15,2014,5
4,100678,2014-04-18,Standard,KM-16720,697.074,Kunst Miller,Consumer,California,Los Angeles,9479,211.6125,237.9750,7,2014,4